Ft/navbar
AdelineA/e-commerce-frontend pull request #2
Opened 2024-11-06 10:06 UTC by AdelineA

2024-11-06 14:30 UTC, kareraolivier requested changes
## Few notes
- Create all pages to navigate to
- Create 404 page
- Pages and Routes should not be in components
-

2024-11-06 14:30 UTC, kareraolivier commented on src/Components/Navbar/index.tsx
> +        <NavbarButtons />
this can be navbarIcons

2024-11-06 14:30 UTC, kareraolivier commented on src/Components/Navbar/NavbarButtons/Search.tsx
> +};
search should not be in navbar buttons

2024-11-06 14:30 UTC, kareraolivier commented on src/Components/Navbar/NavbarLinks.tsx
> +        ))}
we need to know active links

2024-11-06 15:05 UTC, AdelineA commented on src/Components/Navbar/index.tsx
> +        <NavbarButtons />
Fixed

2024-11-06 16:30 UTC, AdelineA commented on src/Components/Navbar/NavbarButtons/Search.tsx
> +};
done

2024-11-06 16:31 UTC, AdelineA commented on src/Components/Navbar/NavbarLinks.tsx
> +        ))}
done

2024-11-07 11:48 UTC, kareraolivier requested changes
This is great, I left some minor review

2024-11-07 11:48 UTC, kareraolivier commented on src/Routes/Routes.tsx
> +        element: <Homepage />,
path can be index here

2024-11-07 11:48 UTC, kareraolivier commented on src/Routes/Routes.tsx
> +    children: [
there is no navbar on error page

2024-11-07 11:48 UTC, kareraolivier commented on src/Components/Navbar/Search.tsx
> +    <div className="bg-gray-200 p-2 rounded-lg xl:flex gap-4 hidden">
increase the width of this input

2024-11-08 11:34 UTC, merged